@startuml
skinparam BackgroundColor white
skinparam componentStyle uml2

package "Aplication" {
    [App]
    component "Disk Application" {
        folder "Log"
        note bottom of "Log" : Error\nActivity
        folder "Config"
        note bottom of "Config" : hash.json\nchunk.json
        folder "Storage"
        note bottom of "Storage" : *.bin
        folder "tmp_file"
        note bottom of "tmp_file" : *
        folder "input_file_examples"
        note bottom of "input_file_examples" : *.txt
    }
}

[Config] --> [App]
[App] --> [Log]
[App] <--> [Storage]
[App] <--> [tmp_file]
[input_file_examples] --> [App]
@enduml
