@startuml
skinparam BackgroundColor white
skinparam componentStyle uml2

package "Aplication" {
    component "Disk Application" {
        [App]
        folder "out_application"{
            folder "Log"
            note bottom of "Log" : error.log\nactivity.log
            folder "Storage"
            note bottom of "Storage" : *.bin
            folder "tmp_file"
            note bottom of "tmp_file" : *
            folder "input_file_examples"
            note bottom of "input_file_examples" : *.txt
            folder "collection"{
                folder "Json"
                note bottom of "Json" : hash.json\nchunk.json
                database "SQLite" {
                    [db.collectiondata_base]
                }
            }
        }
    }
}

[collection] <--> [App]
[App] --> [Log]
[App] <--> [Storage]
[App] <--> [tmp_file]
[input_file_examples] --> [App]
@enduml
